[project]
authors = ["hh <i@heysh.xyz>"]
channels = ["conda-forge"]
description = "HH's homemade beancount v3 importers"
name = "beancount-homemade-importers-v3"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
beancount = ">=3.0.0,<4"
beangulp = ">=0.2.0,<0.3"
beanquery = ">=0.2.0,<0.3"
jieba = ">=0.42.1,<0.43"

[pypi-dependencies]
fava = ">=1.30.7, <2"
smart-importer = ">=1.2, <2"
camelot-py = ">=1.0.9, <2"
